import { Component, OnInit } from '@angular/core';
import { Student } from './Interfaces/students.interface';

@Component({
	selector: 'app-students',
	templateUrl: './students.component.html',
	styleUrls: ['./students.component.scss'],
})
export class StudentsComponent implements OnInit {
	// Lista de datos par las tablas
	activeStudents: Student[] = [
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
		},
	];

	inactiveStudents: Student[] = [
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 50,
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 70,
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			total_hours: 90,
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 30,
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			total_hours: 50,
		},
	];

	approvedStudents: Student[] = [
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 20,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 20,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 20,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 20,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Jhonattan',
			last_name: 'Garcia',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 70,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Angela',
			last_name: 'Torrealba',
			identification: 5651132,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 90,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Luis',
			last_name: 'Sierra',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 20,
			date_approval: '3-09-2022',
		},
		{
			first_name: 'Leonel',
			last_name: 'Loyo',
			identification: 12345678,
			career: 'Computacion',
			project: 'Sistema de SC',
			total_hours: 50,
			date_approval: '3-09-2022',
		},
	];

	// Lista de Headers
	activeStudentHeaders: string[] = [
		'Nombre',
		'Apellido',
		'Cedula',
		'Carrera',
		'Proyecto',
		'Horas',
	];

	inactiveStudentHeaders: string[] = [
		'Nombre',
		'Apellido',
		'Cedula',
		'Carrera',
		'Horas',
	];

	approvedStudentHeaders: string[] = [
		'Nombre',
		'Apellido',
		'Cedula',
		'Carrera',
		'Proyecto',
		'Horas',
		'Fecha de aprobación',
	];

	constructor() {}

	ngOnInit(): void {}
}
